### ISSUE TITLE
BACKEND - Create Schemas for Items/Spells and the relation between Characters and Items/Spells

### ISSUE THREAD

**Issue by UFdylantosh** [Charlene999/CEN3031-The-Perfect-Path#33]

**Comment by kerryhannigan** [comment]
#4

**Comment by cwojtak** [comment]
Currently SpellIds and ItemIds are stored in the Character schema as a string; can you migrate this to another relation schema?

**Comment by kerryhannigan** [comment]
#90 - Pull Request

**Comment by cwojtak** [comment]
Fleshed out the schemas a little more with class and level requirements
Also added one quick foreign key attribute for OwnerId in Character
See PR #92
